### ISSUE TITLE
Failed on big dataset with struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by frankl1** [XAIseries/XEM#1]
Hello,

I am trying to run XEM on a dataset. The algorithm works well on `BasicMotion`, but it failed when I used more than one tree on my dataset which contains about 6278 MTS (6 dimensions) in the train set. I suspect the error to be in the joblib library but I am not sure. Here is the traceback:

```
Number of MTS in train set: 6278
Number of MTS in test set: 1570
Number of classes: 14
MTS length: 261
Window size: 52
Number of features: 5

Cross-validation - folds: 1, current: 0
Training set size: 1318380
Validation set size: 0
Testing set size: 329700
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 357, in _sendback_result
    exception=exception))
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 247, in put
    self._writer.send_bytes(obj)
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./main.py", line 47, in <module>
    clf.fit(X_train[:,2:], y_train)
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/site-packages/lce/_lce.py", line 424, in fit
    self.estimators_.fit(X, y)
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/site-packages/sklearn/ensemble/_bagging.py", line 269, in fit
    return self._fit(X, y, self.max_samples, sample_weight=sample_weight)
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/site-packages/sklearn/ensemble/_bagging.py", line 407, in _fit
    for i in range(n_jobs)
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/local.isima.fr/mfmbouopda/miniconda3/envs/shapeletnet/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
srun: error: node36: task 0: Exited with exit code 1
```

There is no problem when I use a single tree.

**Comment by XAIseries** [comment]
Hello,

Thank you for your message.
Could you please confirm that you are using the latest version of the package lcensemble (v0.2.7)?

Best,

**Comment by frankl1** [comment]
I installed it recently, it is v0.2.6 that I am using. 
Let me update it and re-run the experiment.

**Comment by frankl1** [comment]
I updated the lcensemble package from 0.2.6 to 0.2.7 and re-run my experiment.   

<img width="598" alt="image" src="https://user-images.githubusercontent.com/23366578/180885027-09fb61a6-1f97-49f9-b951-a96cea2751d0.png"> 

Unfortunately, the code failed with the exact same error.

**Comment by XAIseries** [comment]
Hello,

Thank you for your message.
I will try to reproduce the error, are you using a public dataset?

Best,

**Comment by frankl1** [comment]
Alright, that's cool.

Here is the dataset: https://drive.uca.fr/f/362571389ba04f299dda/?dl=1 

And the configuration file:
``` 
{
    "experiment_run": 1,
    "dataset": "plasticc",
    "validation_split": [1,0],
    "window": 0.2,
    "trees": 2,
    "max_depth": 1,
    "max_samples": 0.8,
    "n_jobs": -1,
    "random_state": 0,
    'criterion': 'entropy'
    
    # The other parameters of LCE can be added and modified in this configuration file (current=default values) 
    # Please see LCE API documentation: https://lce.readthedocs.io/en/latest/generated/lce.LCEClassifier.html
}
```

**Comment by XAIseries** [comment]
Hello,

Thank you very much for sharing the dataset and your configuration file.

I have tried on both Linux and Windows and I have not encountered any error (see results below).
Here is the procedure I followed:

- Download XEM GitHub repository
- Download of your dataset and configuration file
- Add `criterion=configuration["criterion"]` to LCEClassifier in `main.py` (parameter you added to the initial configuration file)
- Create a new environment: `conda create -n xem python=3.8`
- Activate the new environment: `conda activate xem`
- Install the required packages: `pip install lcensemble pyarrow pyyaml`
- Run the experiment: `python main.py --config configuration/config.yml`

And I obtained the following results:

<img width="209" alt="results" src="https://user-images.githubusercontent.com/95345072/181814385-acba96ef-d6bf-4b91-81f7-297f979cf171.PNG">

Could you please run this procedure to see if you still get the same error?

Thank you in advance.

Best,

**Comment by frankl1** [comment]
Hello,

Thank for what you have done. I have followed the procedure and it worked. I guess the problem was because I was using Python 3.7 and not Python 3.8.

Best,
